# Generated by Django 5.2.1 on 2025-05-21 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='documentation_image')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('passport', models.CharField(max_length=15)),
                ('id_card', models.CharField(blank=True, max_length=15, null=True)),
                ('hvhh', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.CharField(blank=True, max_length=30, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='person')),
            ],
        ),
        migrations.CreateModel(
            name='OfficialProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
                ('year', models.CharField(max_length=4)),
                ('number', models.CharField(max_length=20)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='official_property', to='employee.person')),
            ],
        ),
        migrations.CreateModel(
            name='Informations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('about', models.TextField(blank=True, null=True)),
                ('img', models.ManyToManyField(blank=True, null=True, to='employee.documentationimage')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informations', to='employee.person')),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('position_start', models.CharField(max_length=255)),
                ('data_of_start', models.DateField(blank=True, null=True)),
                ('end_of_start', models.DateField(blank=True, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='employee.person')),
            ],
        ),
        migrations.AddField(
            model_name='documentationimage',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentation_image', to='employee.person'),
        ),
        migrations.CreateModel(
            name='Conviction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_article', models.CharField(max_length=255)),
                ('from_year', models.CharField(max_length=4)),
                ('to_year', models.CharField(max_length=4)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conviction', to='employee.person')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=15)),
                ('model', models.CharField(max_length=10)),
                ('year', models.CharField(max_length=4)),
                ('number', models.CharField(max_length=10)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car', to='employee.person')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=50)),
                ('house', models.CharField(max_length=20)),
                ('apartment', models.CharField(blank=True, max_length=20, null=True)),
                ('registration', models.CharField(choices=[('Հ', 'Հաշվառման'), ('Բ', 'Բնակության'), ('Ս', 'Սեփականություն')], max_length=1)),
                ('person', models.ManyToManyField(to='employee.person')),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone', to='employee.person')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.ManyToManyField(to='employee.address')),
                ('person', models.ManyToManyField(to='employee.person')),
            ],
        ),
        migrations.CreateModel(
            name='Relatives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatives', to='employee.employees')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatives', to='employee.person')),
            ],
        ),
        migrations.CreateModel(
            name='Soldier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('where', models.CharField(max_length=255)),
                ('from_year', models.CharField(max_length=4)),
                ('to_year', models.CharField(max_length=4)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soldier', to='employee.person')),
            ],
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('educational_institution', models.CharField(max_length=255)),
                ('facultet', models.CharField(max_length=255)),
                ('profession', models.CharField(max_length=50)),
                ('start_year', models.CharField(max_length=4)),
                ('end_year', models.CharField(max_length=4)),
                ('img', models.ImageField(upload_to='documentations')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study', to='employee.person')),
            ],
        ),
        migrations.CreateModel(
            name='VictimsAwards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('data_of_victims_or_awards', models.DateField(blank=True, null=True)),
                ('person', models.ManyToManyField(to='employee.employees')),
            ],
        ),
    ]
