# Generated by Django 5.2.1 on 2025-05-16 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('passport', models.CharField(max_length=15)),
                ('id_card', models.CharField(max_length=15)),
                ('hvhh', models.IntegerField(blank=True, null=True)),
                ('email', models.CharField(max_length=30)),
                ('img', models.ImageField(upload_to='person')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=15)),
                ('model', models.CharField(max_length=10)),
                ('year', models.CharField(max_length=4)),
                ('number', models.CharField(max_length=10)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car', to='employee.employees')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('street', models.CharField(max_length=20)),
                ('house', models.CharField(max_length=10)),
                ('apartment', models.CharField(blank=True, max_length=10, null=True)),
                ('employee', models.ManyToManyField(to='employee.employees')),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone', to='employee.employees')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.ManyToManyField(to='employee.address')),
                ('employee', models.ManyToManyField(to='employee.employees')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='documentations')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='employee.property')),
            ],
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facultet', models.CharField(max_length=255)),
                ('profession', models.CharField(max_length=50)),
                ('start_year', models.CharField(max_length=4)),
                ('end_year', models.CharField(max_length=4)),
                ('img', models.ImageField(upload_to='documentations')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study', to='employee.employees')),
            ],
        ),
    ]
