# Generated by Django 5.2.1 on 2025-05-19 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='educational_institution',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Informations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('about', models.TextField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informations', to='employee.employees')),
                ('img', models.ManyToManyField(blank=True, null=True, to='employee.documentationimage')),
            ],
        ),
        migrations.CreateModel(
            name='OfficialProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
                ('year', models.CharField(max_length=4)),
                ('number', models.CharField(max_length=20)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='official_property', to='employee.employees')),
            ],
        ),
        migrations.CreateModel(
            name='StartKariera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_start', models.CharField(max_length=255)),
                ('data_of_start', models.DateField(blank=True, null=True)),
                ('position_end', models.CharField(blank=True, max_length=255, null=True)),
                ('end_of_start', models.DateField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_kariera', to='employee.employees')),
                ('img', models.ManyToManyField(blank=True, null=True, to='employee.documentationimage')),
            ],
        ),
        migrations.CreateModel(
            name='VictimsAwards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('data_of_victims_or_awards', models.DateField(blank=True, null=True)),
                ('employee', models.ManyToManyField(to='employee.employees')),
            ],
        ),
    ]
