# Generated by Django 5.2.1 on 2025-05-27 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_officialproperty_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='passport',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
