# Generated by Django 5.2.1 on 2025-05-19 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_study_educational_institution_informations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informations',
            name='img',
            field=models.ManyToManyField(to='employee.documentationimage'),
        ),
        migrations.AlterField(
            model_name='startkariera',
            name='img',
            field=models.ManyToManyField(to='employee.documentationimage'),
        ),
    ]
