# Generated by Django 5.2.1 on 2025-05-29 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_person_passport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends', to='employee.employees')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends', to='employee.person')),
            ],
        ),
        migrations.CreateModel(
            name='Pals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pals', to='employee.employees')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pals', to='employee.person')),
            ],
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relation', to='employee.employees')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relation', to='employee.person')),
            ],
        ),
    ]
