# Generated by Django 5.2.1 on 2025-06-02 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_friends_pals_relation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friends',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='pals',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='relation',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='relatives',
            name='employee',
        ),
        migrations.AlterField(
            model_name='friends',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends_2', to='employee.person'),
        ),
        migrations.AlterField(
            model_name='pals',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pals_2', to='employee.person'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relation_2', to='employee.person'),
        ),
    ]
