# Generated by Django 5.2.1 on 2025-06-02 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_remove_friends_employee_remove_pals_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='friends',
            name='friends',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='friends_2', to='employee.person'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pals',
            name='pals',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pals_2', to='employee.person'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='relation',
            name='relation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='relation_2', to='employee.person'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='relatives',
            name='relatives',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='relatives_2', to='employee.person'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='friends',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends_1', to='employee.person'),
        ),
        migrations.AlterField(
            model_name='pals',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pals_1', to='employee.person'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relation_1', to='employee.person'),
        ),
        migrations.AlterField(
            model_name='relatives',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatives_1', to='employee.person'),
        ),
    ]
