from django.urls import path
from .views import (
    GetMe,
    GetRegionList,
    GetPrecinctList,
    GetPositionList,
    AddEmployee,
    GetLastEmployee,
    GetLastCar,
    GetLastRoute,
    GetStationShiftList,
    FilterStationShift,
    AddStationShift,
    GetStationShift,
    AddRoute,
    GetEmployee,
    GetRouteMap,
    AddInformationForShift,
    GetInformationForShift,
    start_lunch,
    end_lunch,
    get_lunches
)

urlpatterns = [
    path('getme/', GetMe.as_view()),
    path('regions/', GetRegionList.as_view()),
    path('precinct/', GetPrecinctList.as_view()),
    path('position/', GetPositionList.as_view()),
    path('addEmployee/', AddEmployee.as_view()),
    path('getlastemployee/', GetLastEmployee.as_view()),
    path('getemployee/<int:pk>/', GetEmployee.as_view()),
    path('getlastcar/', GetLastCar.as_view()),
    path('getlastroute/', GetLastRoute.as_view()),
    path('getstationshiftlist/', GetStationShiftList.as_view()),
    path('filterstationshift/', FilterStationShift.as_view()),
    path('getstationshift/<int:pk>/', GetStationShift.as_view()),
    path('addstationshift/', AddStationShift.as_view()),
    path('addroute/', AddRoute.as_view()),
    path('routes/<int:pk>/', GetRouteMap.as_view()),
    path('addinformationforshift/', AddInformationForShift.as_view()),
    path('getinformationforshift/', GetInformationForShift.as_view()),
    path('lunch_start/', start_lunch, name='start_lunch'),
    path("lunch_end/", end_lunch, name="end_lunch"),
    path("lunches/", get_lunches, name="get_lunches"),
]
