# Generated by Django 5.2.1 on 2026-02-27 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_number', models.CharField(max_length=7)),
                ('board_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_held', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_number', models.IntegerField()),
                ('route_length', models.IntegerField()),
                ('route_img', models.ImageField(blank=True, null=True, upload_to='route_images/')),
            ],
        ),
        migrations.CreateModel(
            name='ProtectedAreas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protected_areas', models.CharField(blank=True, max_length=50, null=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protectedareas', to='person.region')),
            ],
        ),
        migrations.CreateModel(
            name='Precinct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precinct', models.CharField(max_length=50)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precinct', to='person.region')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('camera', models.IntegerField(blank=True, null=True)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='person.position')),
                ('precinct', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='person.precinct')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='person.region')),
            ],
        ),
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserve', models.CharField(blank=True, max_length=50, null=True)),
                ('protected_areas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserve', to='person.protectedareas')),
            ],
        ),
        migrations.CreateModel(
            name='StationShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_shift', models.DateTimeField()),
                ('end_shift', models.DateTimeField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stationshift', to='person.car')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stationshift', to=settings.AUTH_USER_MODEL)),
                ('employee_01', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stationshift', to='person.employee')),
                ('employee_02', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stationshift_02', to='person.employee')),
                ('employee_03', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stationshift_03', to='person.employee')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stationshift', to='person.position')),
                ('precinct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stationshift', to='person.precinct')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stationshift', to='person.region')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stationshift', to='person.route')),
            ],
        ),
    ]
