# Generated by Django 5.2.1 on 2025-06-05 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plase_name', models.CharField(max_length=255)),
                ('position_start', models.CharField(max_length=255)),
                ('data_of_start', models.DateField(blank=True, null=True)),
                ('end_of_start', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='person')),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('passport', models.CharField(blank=True, max_length=15, null=True)),
                ('id_card', models.CharField(blank=True, max_length=15, null=True)),
                ('hvhh', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OfficialProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
                ('year', models.CharField(max_length=4)),
                ('number', models.CharField(max_length=20)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='official_property', to='person.employees')),
            ],
        ),
        migrations.CreateModel(
            name='Informations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('about', models.TextField(blank=True, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informations', to='person.person')),
            ],
        ),
        migrations.AddField(
            model_name='employees',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='person.person'),
        ),
        migrations.CreateModel(
            name='Conviction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_article', models.CharField(max_length=255)),
                ('from_year', models.CharField(max_length=4)),
                ('to_year', models.CharField(max_length=4)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conviction', to='person.person')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=15)),
                ('model', models.CharField(max_length=10)),
                ('year', models.CharField(max_length=4)),
                ('number', models.CharField(max_length=10)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car', to='person.person')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=50)),
                ('house', models.CharField(max_length=20)),
                ('apartment', models.CharField(blank=True, max_length=20, null=True)),
                ('registration', models.CharField(choices=[('Հ', 'Հաշվառման'), ('Բ', 'Բնակության'), ('Ս', 'Սեփականություն')], max_length=1)),
                ('img', models.ImageField(blank=True, null=True, upload_to='person_documentation')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='person.person')),
            ],
        ),
        migrations.CreateModel(
            name='PersonDocumentationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='person_documentation')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_documentation', to='person.person')),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('home', models.BooleanField(default=False)),
                ('mobile', models.BooleanField(default=False)),
                ('viber', models.BooleanField(default=False)),
                ('whatsUp', models.BooleanField(default=False)),
                ('telegram', models.BooleanField(default=False)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone', to='person.person')),
            ],
        ),
        migrations.CreateModel(
            name='Relatives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pal_name', models.CharField(max_length=15)),
                ('registration', models.CharField(choices=[('Բ', 'Բարեկամներ'), ('Ը', 'Ընկերներ'), ('Կ', 'Կապեր')], max_length=1)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatives_1', to='person.person')),
                ('relatives', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatives_2', to='person.person')),
            ],
        ),
        migrations.CreateModel(
            name='Soldier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('where', models.CharField(max_length=255)),
                ('from_year', models.CharField(max_length=4)),
                ('to_year', models.CharField(max_length=4)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soldier', to='person.person')),
            ],
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('educational_institution', models.CharField(max_length=255)),
                ('facultet', models.CharField(max_length=255)),
                ('profession', models.CharField(max_length=50)),
                ('start_year', models.CharField(max_length=4)),
                ('end_year', models.CharField(max_length=4)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study', to='person.person')),
            ],
        ),
        migrations.CreateModel(
            name='VictimsAwards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('data_of_victims_or_awards', models.DateField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='victims_awards', to='person.employees')),
            ],
        ),
    ]
