# Generated by Django 5.2.1 on 2026-02-27 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='region',
            old_name='region',
            new_name='name',
        ),
    ]
