# Generated by Django 5.2.1 on 2025-06-06 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatives',
            name='registration',
            field=models.CharField(choices=[('Հ', 'Հարազատներ'), ('Բ', 'Բարեկամներ'), ('Ը', 'Ընկերներ'), ('Կ', 'Կապեր')], max_length=1),
        ),
    ]
