# Generated by Django 5.2.1 on 2025-06-06 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_alter_relatives_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='degree',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
