# Generated by Django 5.2.1 on 2026-02-27 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_rename_region_region_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='region',
            old_name='name',
            new_name='region',
        ),
    ]
