# Generated by Django 5.2.1 on 2026-02-27 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_rename_name_region_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserve',
            name='protected_areas',
        ),
        migrations.DeleteModel(
            name='ProtectedAreas',
        ),
        migrations.DeleteModel(
            name='Reserve',
        ),
    ]
