# Generated by Django 5.2.1 on 2025-06-09 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_employees_degree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='registration',
            field=models.CharField(choices=[('Հաշվառման', 'Հ'), ('Բնակության', 'Բ'), ('Սեփականություն', 'Ս')], max_length=15),
        ),
    ]
