# Generated by Django 5.2.1 on 2026-02-27 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0004_remove_reserve_protected_areas_delete_protectedareas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='route_img',
        ),
        migrations.AddField(
            model_name='route',
            name='route_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='route',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
