# Generated by Django 5.2.1 on 2026-02-27 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0005_remove_route_route_img_route_route_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='route_image',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='route',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='map'),
        ),
    ]
