# Generated by Django 5.2.1 on 2026-02-27 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0006_rename_route_image_route_image_alter_route_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='precinct',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='route', to='person.precinct'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='route', to='person.region'),
            preserve_default=False,
        ),
    ]
