# Generated by Django 5.2.1 on 2026-02-27 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0007_route_precinct_route_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='route_number',
            field=models.CharField(max_length=15),
        ),
    ]
