# Generated by Django 5.2.1 on 2025-06-12 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0007_alter_address_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='person_study'),
        ),
    ]
