# Generated by Django 5.2.1 on 2025-06-12 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0008_study_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='place',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
