# Generated by Django 5.2.1 on 2026-02-27 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0008_alter_route_route_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stationshift',
            name='position',
        ),
    ]
