# Generated by Django 5.2.1 on 2025-06-13 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0009_study_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informations',
            name='name',
        ),
        migrations.AddField(
            model_name='informations',
            name='politics',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='informations',
            name='religion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='informations',
            name='sex',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
