# Generated by Django 5.2.1 on 2026-02-27 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0009_remove_stationshift_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
