# Generated by Django 5.2.1 on 2026-01-19 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0010_remove_informations_name_informations_politics_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='person',
        ),
        migrations.RemoveField(
            model_name='conviction',
            name='person',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='victimsawards',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='officialproperty',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='informations',
            name='person',
        ),
        migrations.RemoveField(
            model_name='persondocumentationimage',
            name='person',
        ),
        migrations.RemoveField(
            model_name='relatives',
            name='person',
        ),
        migrations.RemoveField(
            model_name='relatives',
            name='relatives',
        ),
        migrations.RemoveField(
            model_name='soldier',
            name='person',
        ),
        migrations.RemoveField(
            model_name='study',
            name='person',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.DeleteModel(
            name='Conviction',
        ),
        migrations.DeleteModel(
            name='VictimsAwards',
        ),
        migrations.DeleteModel(
            name='Employees',
        ),
        migrations.DeleteModel(
            name='OfficialProperty',
        ),
        migrations.DeleteModel(
            name='Informations',
        ),
        migrations.DeleteModel(
            name='PersonDocumentationImage',
        ),
        migrations.DeleteModel(
            name='Relatives',
        ),
        migrations.DeleteModel(
            name='Soldier',
        ),
        migrations.DeleteModel(
            name='Study',
        ),
    ]
