# Generated by Django 5.2.1 on 2026-03-06 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0010_alter_employee_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationshift',
            name='employee_04',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stationshift_04', to='person.employee'),
        ),
    ]
