# Generated by Django 5.2.1 on 2026-01-19 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0011_remove_car_person_remove_conviction_person_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration', models.CharField(choices=[('Սյունիք', 'ՀՀ Սյունիքի մարզային վարչություն'), ('Կոտայք և Գեղարքունիք', 'ՀՀ Կոտայքի և Գեղարքունիքի մարզային վարչություն'), ('Տավուշ', 'ՀՀ Տավուշի մարզային վարչություն'), ('Լոռի', 'ՀՀ Լոռու մարզային վարչություն'), ('Վայոց ձոր և Արարատ', 'ՀՀ Վայոց ձորի և Արարատի մարզային վարչություն'), ('Շիրակ և Արագածոտն', 'ՀՀ Շիրակի և Արագածոտնի մարզային վարչություն'), ('Երևան և Արմավիր', 'Երևան քաղաքի և ՀՀ Արմավիրի մարզային վարչություն')], max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='phone',
            name='person',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='Phone',
        ),
    ]
