# Generated by Django 5.2.1 on 2026-01-19 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0012_region_remove_phone_person_delete_person_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Precinct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=50)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precinct', to='person.region')),
            ],
        ),
    ]
