# Generated by Django 5.2.1 on 2026-03-09 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0012_useraccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccess',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='person.region'),
            preserve_default=False,
        ),
    ]
