# Generated by Django 5.2.1 on 2026-01-19 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0013_precinct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='registration',
        ),
        migrations.AddField(
            model_name='region',
            name='region',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
