# Generated by Django 5.2.1 on 2026-03-09 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0013_useraccess_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='camera',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
