# Generated by Django 5.2.1 on 2026-01-19 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0014_remove_region_registration_region_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_held', models.CharField(max_length=50)),
            ],
        ),
    ]
