# Generated by Django 5.2.1 on 2026-03-15 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0015_employee_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='car', to='person.region'),
            preserve_default=False,
        ),
    ]
