# Generated by Django 5.2.1 on 2026-01-19 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0015_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='person.position')),
                ('precinct', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='person.precinct')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='person.region')),
            ],
        ),
    ]
