# Generated by Django 5.2.1 on 2026-01-20 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0017_citizen_regionarmenia'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallToAin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call', models.BooleanField(default=False)),
                ('call_of_date', models.DateField(blank=True, null=True)),
                ('why_not', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InfoAboutFire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_of_fire', models.DateField(blank=True, null=True)),
                ('from_where', models.CharField(blank=True, max_length=100, null=True)),
                ('the_source_of_the_fire', models.CharField(blank=True, max_length=250, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('section', models.CharField(blank=True, max_length=250, null=True)),
                ('place', models.CharField(blank=True, max_length=250, null=True)),
                ('registration', models.CharField(choices=[('Պ', 'Պետական պահպանվող տարածք'), ('Հ', 'Համայնքային տարածք')], max_length=1)),
                ('forest_place', models.CharField(blank=True, max_length=4, null=True)),
                ('field_place', models.CharField(blank=True, max_length=4, null=True)),
                ('burnt_trees', models.CharField(blank=True, max_length=3, null=True)),
                ('burnt_animals', models.CharField(blank=True, max_length=2, null=True)),
                ('end_of_fire', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OperationalControlCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('date_call', models.DateTimeField(auto_now_add=True)),
                ('call_ain', models.DateTimeField(blank=True, null=True)),
                ('ain_name', models.CharField(max_length=100)),
                ('call_region', models.DateTimeField(blank=True, null=True)),
                ('region_name', models.CharField(max_length=100)),
                ('հead_of_the_occ', models.DateTimeField(blank=True, null=True)),
                ('հead_of_the_occ_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ParticipationGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eps', models.CharField(blank=True, max_length=250, null=True)),
                ('ain', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='RegionArmenia',
        ),
    ]
