# Generated by Django 5.2.1 on 2026-03-26 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0017_route_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='kmz_file',
            field=models.FileField(blank=True, null=True, upload_to='kmz/'),
        ),
    ]
