# Generated by Django 5.2.1 on 2026-03-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0018_route_kmz_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='birth_day',
            field=models.DateField(blank=True, null=True, verbose_name='Ծննդյան ամսաթիվ'),
        ),
        migrations.AddField(
            model_name='employee',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='person'),
        ),
        migrations.AddField(
            model_name='employee',
            name='residential_address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='service_number',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
