# Generated by Django 5.2.1 on 2026-01-21 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0018_calltoain_infoaboutfire_operationalcontrolcenter_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CallToAin',
        ),
        migrations.DeleteModel(
            name='ParticipationGroups',
        ),
        migrations.RenameField(
            model_name='infoaboutfire',
            old_name='field_place',
            new_name='field_place_burnt',
        ),
        migrations.RenameField(
            model_name='infoaboutfire',
            old_name='forest_place',
            new_name='forest_place_burnt',
        ),
        migrations.AddField(
            model_name='infoaboutfire',
            name='ain',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='infoaboutfire',
            name='call',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='infoaboutfire',
            name='call_of_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='infoaboutfire',
            name='citizen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='infoaboutfire', to='person.citizen'),
        ),
        migrations.AddField(
            model_name='infoaboutfire',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='infoaboutfire', to='person.employee'),
        ),
        migrations.AddField(
            model_name='infoaboutfire',
            name='eps',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='infoaboutfire',
            name='why_not',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='operationalcontrolcenter',
            name='infoaboutfire',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='operationalcontrolcenter', to='person.infoaboutfire'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='operationalcontrolcenter',
            name='ain_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='operationalcontrolcenter',
            name='region_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='operationalcontrolcenter',
            name='հead_of_the_occ_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
