# Generated by Django 5.2.1 on 2026-01-21 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0019_delete_calltoain_delete_participationgroups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoaboutfire',
            name='call_of_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='infoaboutfire',
            name='end_of_fire',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='infoaboutfire',
            name='start_of_fire',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
