# Generated by Django 5.2.1 on 2026-03-27 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0019_employee_birth_day_employee_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='passport',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
