# Generated by Django 5.2.1 on 2026-01-21 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0020_alter_infoaboutfire_call_of_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionArmenia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='infoaboutfire',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='infoaboutfire', to='person.regionarmenia'),
            preserve_default=False,
        ),
    ]
