# Generated by Django 5.2.1 on 2026-01-21 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0021_regionarmenia_alter_infoaboutfire_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='citizen', to='person.regionarmenia'),
        ),
    ]
