# Generated by Django 5.2.1 on 2026-03-27 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0021_employee_order_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='camera',
            field=models.IntegerField(unique=True, verbose_name='Տեսախցիկ'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Անուն'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='passport',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Անձնագիր'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='Հեռ.'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='person.position', verbose_name='Պաշտոն'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='precinct',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='person.precinct', verbose_name='Տեղամաս'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='person.region', verbose_name='Վարչություն'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='residential_address',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Հեռ.'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='service_number',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Ծառայողական համար'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='surname',
            field=models.CharField(max_length=50, verbose_name='Ազգանուն'),
        ),
    ]
