# Generated by Django 5.2.1 on 2026-03-27 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0022_alter_employee_camera_alter_employee_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='person', verbose_name='Նկար'),
        ),
    ]
