# Generated by Django 5.2.1 on 2026-03-27 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0023_alter_employee_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='order_day',
            field=models.DateField(blank=True, null=True, verbose_name='Հրամանի ամսաթիվ'),
        ),
    ]
