# Generated by Django 5.2.1 on 2026-01-21 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0023_cities'),
    ]

    operations = [
        migrations.CreateModel(
            name='Villages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('village', models.CharField(max_length=200)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Cities', to='person.cities')),
            ],
        ),
    ]
