# Generated by Django 5.2.1 on 2026-01-22 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0024_villages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infoaboutfire',
            old_name='call',
            new_name='call_ain',
        ),
        migrations.AlterField(
            model_name='citizen',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='citizen', to='person.cities'),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='citizen', to='person.villages'),
        ),
        migrations.AlterField(
            model_name='operationalcontrolcenter',
            name='date_call',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
