# Generated by Django 5.2.1 on 2026-03-30 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0024_alter_employee_order_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='residential_address',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Բնակության հասցե'),
        ),
    ]
