# Generated by Django 5.2.1 on 2026-03-31 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0025_alter_employee_residential_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='deviceId',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
