# Generated by Django 5.2.1 on 2026-01-23 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0025_rename_call_infoaboutfire_call_ain_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StartCallDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_of_call', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='operationalcontrolcenter',
            name='date_call',
        ),
        migrations.AddField(
            model_name='operationalcontrolcenter',
            name='start_of_call',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='operationalcontrolcenter', to='person.startcalldate'),
            preserve_default=False,
        ),
    ]
