# Generated by Django 5.2.1 on 2026-01-26 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0026_startcalldate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='unknown_person',
            field=models.BooleanField(default=False),
        ),
    ]
