# Generated by Django 5.2.1 on 2026-04-02 07:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0026_car_deviceid'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='registration_day',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
