# Generated by Django 5.2.1 on 2026-01-26 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0027_alter_citizen_unknown_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citizen',
            name='registration',
        ),
    ]
