# Generated by Django 5.2.1 on 2026-04-06 14:13

import apps.person.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0027_route_registration_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationshift',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to=apps.person.models.upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
