# Generated by Django 5.2.1 on 2026-02-02 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0028_remove_citizen_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=200)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Community', to='person.regionarmenia')),
            ],
        ),
        migrations.AlterField(
            model_name='citizen',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='citizen', to='person.community'),
        ),
        migrations.AlterField(
            model_name='villages',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='villages', to='person.community'),
        ),
        migrations.DeleteModel(
            name='Cities',
        ),
    ]
