# Generated by Django 5.2.1 on 2026-04-07 04:52

import apps.person.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0028_stationshift_pdf_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stationshift',
            name='text_info',
            field=models.TextField(blank=True, null=True, verbose_name='Հերթափոխի վերաբերյալ տեղեկություն'),
        ),
        migrations.AlterField(
            model_name='stationshift',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stationshift', to='person.car', verbose_name='Ծառայողական մեքենան'),
        ),
        migrations.AlterField(
            model_name='stationshift',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stationshift', to=settings.AUTH_USER_MODEL, verbose_name='Գրանցող օգտատեր'),
        ),
        migrations.AlterField(
            model_name='stationshift',
            name='employee_01',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stationshift', to='person.employee', verbose_name='Հերթափոխ 1'),
        ),
        migrations.AlterField(
            model_name='stationshift',
            name='employee_02',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stationshift_02', to='person.employee', verbose_name='Հերթափոխ 2'),
        ),
        migrations.AlterField(
            model_name='stationshift',
            name='employee_03',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stationshift_03', to='person.employee', verbose_name='Հերթափոխ 3'),
        ),
        migrations.AlterField(
            model_name='stationshift',
            name='employee_04',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stationshift_04', to='person.employee', verbose_name='Հերթափոխ 4'),
        ),
        migrations.AlterField(
            model_name='stationshift',
            name='end_shift',
            field=models.DateTimeField(verbose_name='Հերթափոխի ավարտ'),
        ),
        migrations.AlterField(
            model_name='stationshift',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to=apps.person.models.upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Հերթափոխի վերաբերյալ զեկուցագիր'),
        ),
        migrations.AlterField(
            model_name='stationshift',
            name='precinct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stationshift', to='person.precinct', verbose_name='Տեղամաս'),
        ),
        migrations.AlterField(
            model_name='stationshift',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stationshift', to='person.region', verbose_name='Մարզ'),
        ),
        migrations.AlterField(
            model_name='stationshift',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stationshift', to='person.route', verbose_name='Երթուղի'),
        ),
        migrations.AlterField(
            model_name='stationshift',
            name='start_shift',
            field=models.DateTimeField(verbose_name='Հերթափոխի սկիզբ'),
        ),
    ]
