# Generated by Django 5.2.1 on 2026-04-07 12:51

import apps.person.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0029_stationshift_text_info_alter_stationshift_car_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stationshift',
            name='pdf_file',
        ),
        migrations.RemoveField(
            model_name='stationshift',
            name='text_info',
        ),
        migrations.CreateModel(
            name='InformationForShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_info', models.TextField(blank=True, null=True, verbose_name='Հերթափոխի վերաբերյալ տեղեկություն')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to=apps.person.models.upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Հերթափոխի վերաբերյալ զեկուցագիր')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informationforshift', to='person.stationshift', verbose_name='Հերթափոխ')),
            ],
        ),
    ]
