# Generated by Django 5.2.1 on 2026-02-02 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0029_community_alter_citizen_city_alter_villages_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='citizen',
            old_name='city',
            new_name='ցommunity',
        ),
        migrations.RenameField(
            model_name='community',
            old_name='city',
            new_name='ցommunity',
        ),
        migrations.RenameField(
            model_name='infoaboutfire',
            old_name='section',
            new_name='ցommunity',
        ),
        migrations.RenameField(
            model_name='villages',
            old_name='city',
            new_name='ցommunity',
        ),
    ]
