# Generated by Django 5.2.1 on 2026-02-02 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0030_rename_city_citizen_ցommunity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='citizen',
            old_name='ցommunity',
            new_name='community',
        ),
        migrations.RenameField(
            model_name='community',
            old_name='ցommunity',
            new_name='community',
        ),
        migrations.RenameField(
            model_name='infoaboutfire',
            old_name='ցommunity',
            new_name='precinct',
        ),
        migrations.RenameField(
            model_name='villages',
            old_name='ցommunity',
            new_name='community',
        ),
        migrations.AddField(
            model_name='infoaboutfire',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='infoaboutfire', to='person.community'),
        ),
    ]
