# Generated by Django 5.2.1 on 2026-04-07 14:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0030_remove_stationshift_pdf_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informationforshift',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='pdf/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Հերթափոխի վերաբերյալ զեկուցագիր'),
        ),
        migrations.AlterField(
            model_name='route',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='map/'),
        ),
    ]
