# Generated by Django 5.2.1 on 2026-02-02 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0031_rename_ցommunity_citizen_community_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ցommunity', to='person.regionarmenia'),
        ),
    ]
