# Generated by Django 5.2.1 on 2026-04-10 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0032_route_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='create_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ստեցծման ամսատիվ'),
        ),
    ]
