# Generated by Django 5.2.1 on 2026-02-03 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0032_alter_community_region'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operationalcontrolcenter',
            old_name='հead_of_the_occ',
            new_name='head_of_the_occ',
        ),
        migrations.RenameField(
            model_name='operationalcontrolcenter',
            old_name='հead_of_the_occ_name',
            new_name='head_of_the_occ_name',
        ),
    ]
