# Generated by Django 5.2.1 on 2026-04-10 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0033_alter_route_create_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='create_date',
        ),
        migrations.AlterField(
            model_name='route',
            name='registration_day',
            field=models.DateField(auto_now_add=True),
        ),
    ]
