# Generated by Django 5.2.1 on 2026-02-03 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0033_rename_հead_of_the_occ_operationalcontrolcenter_head_of_the_occ_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProtectedAreas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protectedareas', to='person.region')),
            ],
        ),
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('protected_areas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserve', to='person.protectedareas')),
            ],
        ),
    ]
