# Generated by Django 5.2.1 on 2026-02-03 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0034_protectedareas_reserve'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infoaboutfire',
            old_name='place',
            new_name='cordinat',
        ),
        migrations.RemoveField(
            model_name='infoaboutfire',
            name='precinct',
        ),
        migrations.AddField(
            model_name='infoaboutfire',
            name='protected_areas',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='infoaboutfire', to='person.protectedareas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infoaboutfire',
            name='reserve',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reserve', to='person.reserve'),
        ),
        migrations.AddField(
            model_name='infoaboutfire',
            name='village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='infoaboutfire', to='person.villages'),
        ),
    ]
