# Generated by Django 6.0.4 on 2026-04-23 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0034_remove_route_create_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='person/', verbose_name='Նկար'),
        ),
    ]
