# Generated by Django 5.2.1 on 2026-02-03 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0035_rename_place_infoaboutfire_cordinat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='community',
            old_name='community',
            new_name='name',
        ),
    ]
