# Generated by Django 6.0.4 on 2026-05-06 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0035_alter_employee_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='LunchTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_lanch', models.TimeField()),
                ('end_lanch', models.TimeField()),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lunchtime', to='person.stationshift', verbose_name='Հերթափոխ')),
            ],
        ),
    ]
