# Generated by Django 5.2.1 on 2026-02-03 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0036_rename_community_community_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='region',
            old_name='region',
            new_name='name',
        ),
    ]
