# Generated by Django 6.0.4 on 2026-05-06 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0036_lunchtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lunchtime',
            name='end_lanch',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
