# Generated by Django 6.0.4 on 2026-05-06 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0037_alter_lunchtime_end_lanch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lunchtime',
            name='start_lanch',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
