# Generated by Django 5.2.1 on 2026-02-03 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0037_rename_region_region_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='regionarmenia',
            old_name='region',
            new_name='name',
        ),
    ]
