# Generated by Django 5.2.1 on 2026-02-03 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0038_rename_region_regionarmenia_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='villages',
            old_name='village',
            new_name='name',
        ),
    ]
