# Generated by Django 6.0.4 on 2026-05-06 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0038_alter_lunchtime_start_lanch'),
    ]

    operations = [
        migrations.AddField(
            model_name='lunchtime',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
