# Generated by Django 5.2.1 on 2026-02-04 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0039_rename_village_villages_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infoaboutfire',
            old_name='end_of_fire',
            new_name='date_and_time',
        ),
        migrations.RenameField(
            model_name='precinct',
            old_name='section',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='infoaboutfire',
            name='ain',
        ),
        migrations.RemoveField(
            model_name='infoaboutfire',
            name='burnt_animals',
        ),
        migrations.RemoveField(
            model_name='infoaboutfire',
            name='burnt_trees',
        ),
        migrations.RemoveField(
            model_name='infoaboutfire',
            name='eps',
        ),
        migrations.RemoveField(
            model_name='infoaboutfire',
            name='field_place_burnt',
        ),
        migrations.RemoveField(
            model_name='infoaboutfire',
            name='forest_place_burnt',
        ),
        migrations.AddField(
            model_name='infoaboutfire',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='infoaboutfire',
            name='seurname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='infoaboutfire',
            name='start_of_fire',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='EndFire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_of_fire', models.DateTimeField(blank=True, null=True)),
                ('forest_place_burnt', models.CharField(blank=True, max_length=4, null=True)),
                ('field_place_burnt', models.CharField(blank=True, max_length=4, null=True)),
                ('burnt_trees', models.CharField(blank=True, max_length=3, null=True)),
                ('burnt_animals', models.CharField(blank=True, max_length=2, null=True)),
                ('eps', models.CharField(blank=True, max_length=250, null=True)),
                ('ain', models.CharField(blank=True, max_length=250, null=True)),
                ('infoaboutfire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endfire', to='person.operationalcontrolcenter')),
            ],
        ),
    ]
