# Generated by Django 5.2.1 on 2026-02-05 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0040_rename_end_of_fire_infoaboutfire_date_and_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='infoaboutfire',
            name='regionArmenia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='infoaboutfire', to='person.regionarmenia'),
        ),
        migrations.AlterField(
            model_name='infoaboutfire',
            name='protected_areas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='infoaboutfire', to='person.protectedareas'),
        ),
        migrations.AlterField(
            model_name='infoaboutfire',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='infoaboutfire', to='person.region'),
        ),
    ]
