# Generated by Django 6.0.4 on 2026-04-28 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('person', '0035_alter_employee_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_id', models.CharField(max_length=100, unique=True)),
                ('caller_number', models.CharField(max_length=20)),
                ('called_number', models.CharField(max_length=20)),
                ('call_start', models.DateTimeField(auto_now_add=True)),
                ('call_end', models.DateTimeField(blank=True, null=True)),
                ('call_duration', models.IntegerField(default=0, help_text='seconds')),
                ('recording_url', models.URLField(blank=True, null=True)),
                ('recording_file', models.FileField(blank=True, null=True, upload_to='recordings/%Y/%m/%d/')),
                ('recording_size', models.IntegerField(default=0)),
                ('status', models.CharField(default='initiated', max_length=50)),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='call_records', to='person.stationshift', verbose_name='Հերթափոխ')),
            ],
            options={
                'ordering': ['-call_start'],
            },
        ),
    ]
