# Generated by Django 6.0.4 on 2026-04-20 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('person', '0034_remove_route_create_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=32)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('call_status', models.CharField(default='initiated', max_length=32)),
                ('recording_url', models.URLField(blank=True, null=True)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_records', to='person.stationshift', verbose_name='Հերթափոխ')),
            ],
        ),
    ]
