# Generated by Django 6.0.4 on 2026-04-23 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='callrecord',
            options={'ordering': ['-call_start']},
        ),
        migrations.RenameField(
            model_name='callrecord',
            old_name='started_at',
            new_name='call_start',
        ),
        migrations.RemoveField(
            model_name='callrecord',
            name='call_status',
        ),
        migrations.RemoveField(
            model_name='callrecord',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='callrecord',
            name='call_duration',
            field=models.IntegerField(default=0, help_text='Վայրկյաններով'),
        ),
        migrations.AddField(
            model_name='callrecord',
            name='call_id',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='callrecord',
            name='called_number',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='callrecord',
            name='caller_number',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='callrecord',
            name='recording_file',
            field=models.FileField(blank=True, null=True, upload_to='recordings/'),
        ),
        migrations.AddField(
            model_name='callrecord',
            name='status',
            field=models.CharField(default='initiated', max_length=50),
        ),
    ]
